[package]
name = "api_virtual_shelf"
version = "0.1.0"
authors = ["Ronaldo <rfeitosa@ciandt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
